
package hajji.mohammed.proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "BWS", targetNamespace = "http://mohammed.hajji/", wsdlLocation = "http://localhost:9090/?wsdl")
public class BWS
    extends Service
{

    private static final URL BWS_WSDL_LOCATION;
    private static final WebServiceException BWS_EXCEPTION;
    private static final QName BWS_QNAME = new QName("http://mohammed.hajji/", "BWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9090/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BWS_WSDL_LOCATION = url;
        BWS_EXCEPTION = e;
    }

    public BWS() {
        super(__getWsdlLocation(), BWS_QNAME);
    }

    public BWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), BWS_QNAME, features);
    }

    public BWS(URL wsdlLocation) {
        super(wsdlLocation, BWS_QNAME);
    }

    public BWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BWS_QNAME, features);
    }

    public BWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BanqueService
     */
    @WebEndpoint(name = "BanqueServicePort")
    public BanqueService getBanqueServicePort() {
        return super.getPort(new QName("http://mohammed.hajji/", "BanqueServicePort"), BanqueService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BanqueService
     */
    @WebEndpoint(name = "BanqueServicePort")
    public BanqueService getBanqueServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mohammed.hajji/", "BanqueServicePort"), BanqueService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BWS_EXCEPTION!= null) {
            throw BWS_EXCEPTION;
        }
        return BWS_WSDL_LOCATION;
    }

}
